"""UniLED Effects"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Final
from .helpers import StrEnum

UNILED_EFFECT_TYPE_DYNAMIC: Final = "Dynamic"
UNILED_EFFECT_TYPE_STATIC: Final = "Static"
UNILED_EFFECT_TYPE_SOUND: Final = "Sound"

class UNILEDEffectType(StrEnum):
    """Effect Mode/Type Names"""

    DYNAMIC = UNILED_EFFECT_TYPE_DYNAMIC
    STATIC = UNILED_EFFECT_TYPE_STATIC
    SOUND = UNILED_EFFECT_TYPE_SOUND


class UNILEDEffects(StrEnum):
    """Effect/Pattern Names"""

    BACKGROUND_STARS = "Background Stars"
    BACKGROUND_STARS_RED = "Red Background Stars"
    BACKGROUND_STARS_GREEN = "Green Background Stars"
    BACKGROUND_STARS_BLUE = "Blue Background Stars"
    BACKGROUND_STARS_YELLOW = "Yellow Background Stars"
    BACKGROUND_STARS_CYAN = "Cyan Background Stars"
    BACKGROUND_STARS_PURPLE = "Purple Background Stars"
    BACKGROUND_STARS_RED_WHITE = "Red/White Background Stars"
    BACKGROUND_STARS_GREEN_WHITE = "Green/White Background Stars"
    BACKGROUND_STARS_BLUE_WHITE = "Blue/White Background Stars"
    BACKGROUND_STARS_YELLOW_WHITE = "Yellow/White Background Stars"
    BACKGROUND_STARS_CYAN_WHITE = "Cyan/White Background Stars"
    BACKGROUND_STARS_PURPLE_WHITE = "Purple/White Background Stars"
    BACKGROUND_STARS_WHITE_WHITE = "White/White Background Stars"

    BREATH = "Breath"
    BREATH_RED = "Red Breath"
    BREATH_GREEN = "Green Breath"
    BREATH_BLUE = "Blue Breath"
    BREATH_YELLOW = "Yellow Breath"
    BREATH_CYAN = "Cyan Breath"
    BREATH_PURPLE = "Purple Breath"
    BREATH_WHITE = "White Breath"
    BREATH_SEVEN_COLOR = "Seven Color Breath"

    COMET = "Comet"
    COMET_RED = "Red Comet"
    COMET_GREEN = "Green Comet"
    COMET_BLUE = "Blue Comet"
    COMET_YELLOW = "Yellow Comet"
    COMET_CYAN = "Cyan Comet"
    COMET_PURPLE = "Purple Comet"
    COMET_WHITE = "White Comet"

    COMET_SPIN = "Comet Spin"
    COMET_SPIN_RED = "Red Comet Spin"
    COMET_SPIN_GREEN = "Green Comet Spin"
    COMET_SPIN_BLUE = "Blue Comet Spin"
    COMET_SPIN_YELLOW = "Yellow Comet Spin"
    COMET_SPIN_CYAN = "Cyan Comet Spin"
    COMET_SPIN_PURPLE = "Purple Comet Spin"
    COMET_SPIN_WHITE = "White Comet Spin"

    CUSTOM = "Custom"

    DOT_SPIN = "Dot Spin"
    DOT_SPIN_RED = "Red Dot Spin"
    DOT_SPIN_GREEN = "Green Dot Spin"
    DOT_SPIN_BLUE = "Blue Dot Spin"
    DOT_SPIN_YELLOW = "Yellow Dot Spin"
    DOT_SPIN_CYAN = "Cyan Dot Spin"
    DOT_SPIN_PURPLE = "Purple Dot Spin"
    DOT_SPIN_WHITE = "White Dot Spin"

    FADE = "Fade"

    FIRE = "Fire"
    FIRE_RED_YELLOW = "Red/Yellow Fire"
    FIRE_RED_PURPLE = "Red/Purple Fire"
    FIRE_GREEN_YELLOW = "Green/Yellow Fire"
    FIRE_GREEN_CYAN = "Green/Cyan Fire"
    FIRE_BLUE_PURPLE = "Blue/Purple Fire"
    FIRE_BLUE_CYAN = "Blue/Cyan Fire"

    FLOW = "Flow"
    FLOW_FORWARD = "Flow Forward"
    FLOW_BACKWARD = "Flow Backward"

    GRADIENT = "Gradient"
    GRADIENT_SEVEN_COLOR = "Seven Color Gradient"

    GRADUAL_SNAKE = "Gradual Snake"
    GRADUAL_SNAKE_RED_GREEN = "Red/Green Gradual Snake"
    GRADUAL_SNAKE_RED_BLUE = "Red/Blue Gradual Snake"
    GRADUAL_SNAKE_RED_YELLOW = "Red/Yellow Gradual Snake"
    GRADUAL_SNAKE_RED_CYAN = "Red/Cyan Gradual Snake"
    GRADUAL_SNAKE_RED_PURPLE = "Red/Purple Gradual Snake"
    GRADUAL_SNAKE_RED_WHITE = "Red/White Gradual Snake"
    GRADUAL_SNAKE_GREEN_BLUE = "Green/Blue Gradual Snake"
    GRADUAL_SNAKE_GREEN_YELLOW = "Green/Yellow Gradual Snake"
    GRADUAL_SNAKE_GREEN_CYAN = "Green/Cyan Gradual Snake"
    GRADUAL_SNAKE_GREEN_PURPLE = "Green/Purple Gradual Snake"
    GRADUAL_SNAKE_GREEN_WHITE = "Green/White Gradual Snake"
    GRADUAL_SNAKE_BLUE_YELLOW = "Blue/Yellow Gradual Snake"
    GRADUAL_SNAKE_BLUE_CYAN = "Blue/Cyan Gradual Snake"
    GRADUAL_SNAKE_BLUE_PURPLE = "Blue/Purple Gradual Snake"
    GRADUAL_SNAKE_BLUE_WHITE = "Blue/White Gradual Snake"
    GRADUAL_SNAKE_YELLOW_CYAN = "Yellow/Cyan Gradual Snake"
    GRADUAL_SNAKE_YELLOW_PURPLE = "Yellow/Purple Gradual Snake"
    GRADUAL_SNAKE_YELLOW_WHITE = "Yellow/White Gradual Snake"
    GRADUAL_SNAKE_CYAN_PURPLE = "Cyan/Purple Gradual Snake"
    GRADUAL_SNAKE_CYAN_WHITE = "Cyan/White Gradual Snake"
    GRADUAL_SNAKE_PURPLE_WHITE = "Purple/White Gradual Snake"

    HEARTBEAT = "Heart Beat"
    HEARTBEAT_SEVEN_COLOR = "Seven Color Heart Beat"

    JUMP = "Jump"
    JUMP_SEVEN_COLOR = "Seven Color Jump"

    METEOR = "Meteor"
    METEOR_RED = "Red Meteor"
    METEOR_GREEN = "Green Meteor"
    METEOR_BLUE = "Blue Meteor"
    METEOR_YELLOW = "Yellow Meteor"
    METEOR_CYAN = "Cyan Meteor"
    METEOR_PURPLE = "Purple Meteor"
    METEOR_WHITE = "White Meteor"

    RAINBOW = "Rainbow"
    RAINBOW_METEOR = "Rainbow Metor"
    RAINBOW_STARS = "Rainbow Stars"
    RAINBOW_SPIN = "Rainbow Spin"
    RAINBOW_COMET = "Rainbow Comet"
    RAINBOW_SEGMENT = "Rainbow Segment"
    RAINBOW_WAVE = "Rainbow Wave"
    RAINBOW_JUMP = "Rainbow Jump"

    SEGMENT_SPIN = "Segment Spin"
    SEGMENT_SPIN_RED = "Red Segment Spin"
    SEGMENT_SPIN_GREEN = "Green Segment Spin"
    SEGMENT_SPIN_BLUE = "Blue Segment Spin"
    SEGMENT_SPIN_YELLOW = "Yellow Segment Spin"
    SEGMENT_SPIN_CYAN = "Cyan Segment Spin"
    SEGMENT_SPIN_PURPLE = "Purple Segment Spin"
    SEGMENT_SPIN_WHITE = "White Segment Spin"

    SNAKE = "Snake"
    SNAKE_RED_BLUE_WHITE = "Red/Blue/White Snake"
    SNAKE_GREEN_YELLOW_WHITE = "Green/Yellow/White Snake"
    SNAKE_RED_GREEN_WHITE = "Red/Green/White Snake"
    SNAKE_RED_YELLOW = "Red/Yellow Snake"
    SNAKE_RED_WHITE = "Red/White Snake"
    SNAKE_GREEN_WHITE = "Green/White Snake"

    SOLID = "Solid"
    SOLID_COLOR = "Solid Color"
    SOLID_WHITE = "Solid White"

    STACK = "Stack"
    STACK_FULL_COLOR = "Full Color Stack"
    STACK_RED_GREEN = "Red to Green Stack"
    STACK_GREEN_BLUE = "Green to Blue Stack"
    STACK_BLUE_YELLOW = "Blue to Yellow Stack"
    STACK_YELLOW_CYAN = "Yellow to Cyan Stack"
    STACK_CYAN_PURPLE = "Cyan to Purple Stack"
    STACK_PURPLE_WHITE = "Purple to White Stack"

    STACKING = "Stacking"
    STACKING_RED = "Red Stacking"
    STACKING_GREEN = "Green Stacking"
    STACKING_BLUE = "Blue Stacking"
    STACKING_YELLOW = "Yellow Stacking"
    STACKING_CYAN = "Cyan Stacking"
    STACKING_PRUPLE = "Purple Stacking"
    STACKING_WHITE = "White Stacking"

    STARS = "Stars"
    STARS_TWINKLE = "Twinkle Stars"
    STARS_RED = "Red Stars"
    STARS_GREEN = "Green Stars"
    STARS_BLUE = "Blue Stars"
    STARS_YELLOW = "Yellow Stars"
    STARS_CYAN = "Cyan Stars"
    STARS_PURPLE = "Purple Stars"
    STARS_WHITE = "White Stars"

    STROBE = "Strobe"
    STROBE_RED = "Red Strobe"
    STROBE_GREEN = "Green Strobe"
    STROBE_BLUE = "Blue Strobe"
    STROBE_YELLOW = "Yellow Strobe"
    STROBE_CYAN = "Cyan Strobe"
    STROBE_PURPLE = "Purple Strobe"
    STROBE_WHITE = "White Strobe"
    STROBE_SEVEN_COLOR = "Seven Color Strobe"

    STATIC = "Static"

    WAVE = "Wave"
    WAVE_RED = "Red Wave"
    WAVE_GREEN = "Green Wave"
    WAVE_BLUE = "Blue Wave"
    WAVE_YELLOW = "Yellow Wave"
    WAVE_CYAN = "Cyan Wave"
    WAVE_PURPLE = "Purple Wave"
    WAVE_WHITE = "White Wave"
    WAVE_RED_GREEN = "Red/Green Wave"
    WAVE_RED_BLUE = "Red/Blue Wave"
    WAVE_RED_YELLOW = "Red/Yellow Wave"
    WAVE_RED_CYAN = "Red/Cyan Wave"
    WAVE_RED_PURPLE = "Red/Purple Wave"
    WAVE_RED_WHITE = "Red/White Wave"
    WAVE_GREEN_BLUE = "Green/Blue Wave"
    WAVE_GREEN_YELLOW = "Green/Yellow Wave"
    WAVE_GREEN_CYAN = "Green/Cyan Wave"
    WAVE_GREEN_PURPLE = "Green/Purple Wave"
    WAVE_GREEN_WHITE = "Green/White Wave"
    WAVE_BLUE_YELLOW = "Blue/Yellow Wave"
    WAVE_BLUE_CYAN = "Blue/Cyan Wave"
    WAVE_BLUE_PURPLE = "Blue/Purple Wave"
    WAVE_BLUE_WHITE = "Blue/White Wave"
    WAVE_YELLOW_CYAN = "Yellow/Cyan Wave"
    WAVE_YELLOW_PURPLE = "Yellow/Purple Wave"
    WAVE_YELLOW_WHITE = "Yellow/White Wave"
    WAVE_CYAN_PURPLE = "Cyan/Purple Wave"
    WAVE_CYAN_WHITE = "Cyan/White Wave"
    WAVE_PURPLE_WHITE = "Purple/White Wave"

    # Sound Activated
    SOUND_RHYTHM_SPECTRUM_FULL = "Sound - Full Color Rhythm Spectrum"
    SOUND_RHYTHM_SPECTRUM_SINGLE = "Sound - Single Color Rhythm Spectrum"
    SOUND_RHYTHM_STARS_FULL = "Sound - Full Color Rhythm Stars"
    SOUND_RHYTHM_STARS_SINGLE = "Sound - Single Color Rhythm Stars"
    SOUND_ENERGY_GRADIENT = "Sound - Gradient Energy"
    SOUND_ENERGY_SINGLE = "Sound - Single Color Energy"
    SOUND_PULSE_GRADIENT = "Sound - Gradient Pulse"
    SOUND_PULSE_SINGLE = "Sound - Single Color Pulse"
    SOUND_EJECTION_FORWARD_FULL = "Sound - Full Color Ejection Forward"
    SOUND_EJECTION_FORWARD_SINGLE = "Sound - Single Color Ejection Forward"
    SOUND_EJECTION_BACKWARD_FULL = "Sound - Full Color Ejection Backward"
    SOUND_EJECTION_BACKWARD_SINGLE = "Sound - Single Color Ejection Backward"
    SOUND_VU_METER_FULL = "Sound - Full Color VuMeter"
    SOUND_VU_METER_SINGLE = "Sound - Single Color VuMeter"
    SOUND_LOVE_AND_PEACE = "Sound - Love & Peace"
    SOUND_CHRISTMAS = "Sound - Christmas"
    SOUND_HEARTBEAT = "Sound - Heartbeat"
    SOUND_PARTY = "Sound - Party"

    SOUND_MUSIC_BREATH = "Sound - Music Breath"
    SOUND_MUSIC_JUMP = "Sound - Music Jump"
    SOUND_MUSIC_MONO_BREATH = "Sound - Monochrome Music Breath"
